#############################################################################
# Makefile for building: mirpc_vto
# Generated by qmake (2.01a) (Qt 4.8.7) on: ?? ??? 16 13:08:03 2016
# Project:  mirpc_vto.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -o Makefile mirpc_vto.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_SQL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -std=c++11 -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtSql -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/i386-linux-gnu -lQtSql -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cpp \
		src/MainWindow.cpp \
		src/StateChanFrame.cpp \
		src/MainFrame.cpp \
		src/rightWidget.cpp \
		src/DeviceBut.cpp \
		src/ClockFrame.cpp \
		src/SetNameDialog.cpp \
		src/ChanButton.cpp \
		src/ObjectPA.cpp \
		src/blinkingclass.cpp \
		src/butparent.cpp \
		src/StandBut.cpp \
		src/db/dbclass.cpp \
		src/db/dbMainObject.cpp \
		src/DeviceClass.cpp \
		src/ObjectClass.cpp \
		src/ObjectsUpdater.cpp \
		src/util/MyException.cpp \
		src/db/dbFinder.cpp \
		src/notConnectionDb.cpp \
		src/FaultsClass.cpp \
		src/UbdaterClass.cpp \
		src/baseDevice.cpp \
		src/ActiveDev.cpp \
		src/db/dbDevices.cpp \
		src/BSPurWid.cpp \
		src/PurBut.cpp \
		src/BSPurBut.cpp \
		src/OtherDevWid.cpp \
		src/OtherDevBut.cpp moc_StateChanFrame.cpp \
		moc_DeviceBut.cpp \
		moc_rightWidget.cpp \
		moc_ClockFrame.cpp \
		moc_ChanButton.cpp \
		moc_SetNameDialog.cpp \
		moc_MainWindow.cpp \
		moc_ObjectPA.cpp \
		moc_MainFrame.cpp \
		moc_blinkingclass.cpp \
		moc_butparent.cpp \
		moc_StandBut.cpp \
		moc_frameborder.cpp \
		moc_DeviceClass.cpp \
		moc_ObjectClass.cpp \
		moc_dbFinder.cpp \
		moc_notConnectionDb.cpp \
		moc_UbdaterClass.cpp \
		moc_baseDevice.cpp \
		moc_BSPurWid.cpp \
		moc_OtherDevWid.cpp
OBJECTS       = main.o \
		MainWindow.o \
		StateChanFrame.o \
		MainFrame.o \
		rightWidget.o \
		DeviceBut.o \
		ClockFrame.o \
		SetNameDialog.o \
		ChanButton.o \
		ObjectPA.o \
		blinkingclass.o \
		butparent.o \
		StandBut.o \
		dbclass.o \
		dbMainObject.o \
		DeviceClass.o \
		ObjectClass.o \
		ObjectsUpdater.o \
		MyException.o \
		dbFinder.o \
		notConnectionDb.o \
		FaultsClass.o \
		UbdaterClass.o \
		baseDevice.o \
		ActiveDev.o \
		dbDevices.o \
		BSPurWid.o \
		PurBut.o \
		BSPurBut.o \
		OtherDevWid.o \
		OtherDevBut.o \
		moc_StateChanFrame.o \
		moc_DeviceBut.o \
		moc_rightWidget.o \
		moc_ClockFrame.o \
		moc_ChanButton.o \
		moc_SetNameDialog.o \
		moc_MainWindow.o \
		moc_ObjectPA.o \
		moc_MainFrame.o \
		moc_blinkingclass.o \
		moc_butparent.o \
		moc_StandBut.o \
		moc_frameborder.o \
		moc_DeviceClass.o \
		moc_ObjectClass.o \
		moc_dbFinder.o \
		moc_notConnectionDb.o \
		moc_UbdaterClass.o \
		moc_baseDevice.o \
		moc_BSPurWid.o \
		moc_OtherDevWid.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		mirpc_vto.pro
QMAKE_TARGET  = mirpc_vto
DESTDIR       = 
TARGET        = mirpc_vto

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_rightWidget.h ui_ClockFrame.h ui_SetName.h ui_StateChanFrame.h ui_mainFrame.h ui_ObjectPA.h ui_notConnectionDb.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: mirpc_vto.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/i386-linux-gnu/libQtSql.prl \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile mirpc_vto.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/i386-linux-gnu/libQtSql.prl:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile mirpc_vto.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/mirpc_vto1.0.0 || $(MKDIR) .tmp/mirpc_vto1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/mirpc_vto1.0.0/ && $(COPY_FILE) --parents include/StateChanFrame.h include/DeviceBut.h include/rightWidget.h include/ClockFrame.h include/define.h include/ChanButton.h include/SetNameDialog.h include/MainWindow.h include/ObjectPA.h include/MainFrame.h include/util/Singleton.h include/blinkingclass.h include/butparent.h include/db/dbclass.h include/db/dbMainObject.h include/StandBut.h include/frameborder.h include/DeviceClass.h include/ObjectClass.h include/ObjectsUpdater.h include/util/MyException.h include/db/dbFinder.h include/notConnectionDb.h include/FaultsClass.h include/UbdaterClass.h include/baseDevice.h include/ActiveDev.h include/db/dbDevices.h include/BSPurWid.h include/PurBut.h include/BSPurBut.h include/OtherDevWid.h include/OtherDevBut.h .tmp/mirpc_vto1.0.0/ && $(COPY_FILE) --parents src/main.cpp src/MainWindow.cpp src/StateChanFrame.cpp src/MainFrame.cpp src/rightWidget.cpp src/DeviceBut.cpp src/ClockFrame.cpp src/SetNameDialog.cpp src/ChanButton.cpp src/ObjectPA.cpp src/blinkingclass.cpp src/butparent.cpp src/StandBut.cpp src/db/dbclass.cpp src/db/dbMainObject.cpp src/DeviceClass.cpp src/ObjectClass.cpp src/ObjectsUpdater.cpp src/util/MyException.cpp src/db/dbFinder.cpp src/notConnectionDb.cpp src/FaultsClass.cpp src/UbdaterClass.cpp src/baseDevice.cpp src/ActiveDev.cpp src/db/dbDevices.cpp src/BSPurWid.cpp src/PurBut.cpp src/BSPurBut.cpp src/OtherDevWid.cpp src/OtherDevBut.cpp .tmp/mirpc_vto1.0.0/ && $(COPY_FILE) --parents ui/rightWidget.ui ui/ClockFrame.ui ui/SetName.ui ui/StateChanFrame.ui ui/mainFrame.ui ui/ObjectPA.ui ui/notConnectionDb.ui .tmp/mirpc_vto1.0.0/ && (cd `dirname .tmp/mirpc_vto1.0.0` && $(TAR) mirpc_vto1.0.0.tar mirpc_vto1.0.0 && $(COMPRESS) mirpc_vto1.0.0.tar) && $(MOVE) `dirname .tmp/mirpc_vto1.0.0`/mirpc_vto1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/mirpc_vto1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_StateChanFrame.cpp moc_DeviceBut.cpp moc_rightWidget.cpp moc_ClockFrame.cpp moc_ChanButton.cpp moc_SetNameDialog.cpp moc_MainWindow.cpp moc_ObjectPA.cpp moc_MainFrame.cpp moc_blinkingclass.cpp moc_butparent.cpp moc_StandBut.cpp moc_frameborder.cpp moc_DeviceClass.cpp moc_ObjectClass.cpp moc_dbFinder.cpp moc_notConnectionDb.cpp moc_UbdaterClass.cpp moc_baseDevice.cpp moc_BSPurWid.cpp moc_OtherDevWid.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_StateChanFrame.cpp moc_DeviceBut.cpp moc_rightWidget.cpp moc_ClockFrame.cpp moc_ChanButton.cpp moc_SetNameDialog.cpp moc_MainWindow.cpp moc_ObjectPA.cpp moc_MainFrame.cpp moc_blinkingclass.cpp moc_butparent.cpp moc_StandBut.cpp moc_frameborder.cpp moc_DeviceClass.cpp moc_ObjectClass.cpp moc_dbFinder.cpp moc_notConnectionDb.cpp moc_UbdaterClass.cpp moc_baseDevice.cpp moc_BSPurWid.cpp moc_OtherDevWid.cpp
moc_StateChanFrame.cpp: include/DeviceBut.h \
		include/butparent.h \
		include/baseDevice.h \
		ui_StateChanFrame.h \
		include/define.h \
		include/db/dbDevices.h \
		include/db/dbclass.h \
		include/BSPurWid.h \
		include/ObjectClass.h \
		include/DeviceClass.h \
		include/db/dbMainObject.h \
		include/OtherDevWid.h \
		include/StateChanFrame.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) include/StateChanFrame.h -o moc_StateChanFrame.cpp

moc_DeviceBut.cpp: include/butparent.h \
		include/baseDevice.h \
		include/DeviceBut.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) include/DeviceBut.h -o moc_DeviceBut.cpp

moc_rightWidget.cpp: include/StandBut.h \
		include/butparent.h \
		include/baseDevice.h \
		include/DeviceClass.h \
		ui_rightWidget.h \
		include/ObjectClass.h \
		include/db/dbMainObject.h \
		include/db/dbclass.h \
		include/rightWidget.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) include/rightWidget.h -o moc_rightWidget.cpp

moc_ClockFrame.cpp: ui_ClockFrame.h \
		include/ClockFrame.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) include/ClockFrame.h -o moc_ClockFrame.cpp

moc_ChanButton.cpp: include/butparent.h \
		include/baseDevice.h \
		include/ObjectsUpdater.h \
		include/ObjectClass.h \
		include/DeviceClass.h \
		include/db/dbMainObject.h \
		include/db/dbclass.h \
		include/SetNameDialog.h \
		ui_SetName.h \
		include/ChanButton.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) include/ChanButton.h -o moc_ChanButton.cpp

moc_SetNameDialog.cpp: ui_SetName.h \
		include/SetNameDialog.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) include/SetNameDialog.h -o moc_SetNameDialog.cpp

moc_MainWindow.cpp: include/define.h \
		include/rightWidget.h \
		include/StandBut.h \
		include/butparent.h \
		include/baseDevice.h \
		include/DeviceClass.h \
		ui_rightWidget.h \
		include/ObjectClass.h \
		include/db/dbMainObject.h \
		include/db/dbclass.h \
		include/MainFrame.h \
		ui_mainFrame.h \
		include/StateChanFrame.h \
		include/DeviceBut.h \
		ui_StateChanFrame.h \
		include/db/dbDevices.h \
		include/BSPurWid.h \
		include/OtherDevWid.h \
		include/ChanButton.h \
		include/ObjectsUpdater.h \
		include/SetNameDialog.h \
		ui_SetName.h \
		include/ObjectPA.h \
		include/notConnectionDb.h \
		include/UbdaterClass.h \
		include/db/dbFinder.h \
		include/FaultsClass.h \
		include/ActiveDev.h \
		include/MainWindow.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) include/MainWindow.h -o moc_MainWindow.cpp

moc_ObjectPA.cpp: include/ObjectPA.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) include/ObjectPA.h -o moc_ObjectPA.cpp

moc_MainFrame.cpp: ui_mainFrame.h \
		include/StateChanFrame.h \
		include/DeviceBut.h \
		include/butparent.h \
		include/baseDevice.h \
		ui_StateChanFrame.h \
		include/define.h \
		include/db/dbDevices.h \
		include/db/dbclass.h \
		include/BSPurWid.h \
		include/ObjectClass.h \
		include/DeviceClass.h \
		include/db/dbMainObject.h \
		include/OtherDevWid.h \
		include/ChanButton.h \
		include/ObjectsUpdater.h \
		include/SetNameDialog.h \
		ui_SetName.h \
		include/MainFrame.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) include/MainFrame.h -o moc_MainFrame.cpp

moc_blinkingclass.cpp: include/blinkingclass.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) include/blinkingclass.h -o moc_blinkingclass.cpp

moc_butparent.cpp: include/baseDevice.h \
		include/butparent.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) include/butparent.h -o moc_butparent.cpp

moc_StandBut.cpp: include/butparent.h \
		include/baseDevice.h \
		include/DeviceClass.h \
		include/StandBut.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) include/StandBut.h -o moc_StandBut.cpp

moc_frameborder.cpp: include/frameborder.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) include/frameborder.h -o moc_frameborder.cpp

moc_DeviceClass.cpp: include/baseDevice.h \
		include/DeviceClass.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) include/DeviceClass.h -o moc_DeviceClass.cpp

moc_ObjectClass.cpp: include/DeviceClass.h \
		include/baseDevice.h \
		include/db/dbMainObject.h \
		include/db/dbclass.h \
		include/ObjectClass.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) include/ObjectClass.h -o moc_ObjectClass.cpp

moc_dbFinder.cpp: include/db/dbFinder.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) include/db/dbFinder.h -o moc_dbFinder.cpp

moc_notConnectionDb.cpp: include/notConnectionDb.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) include/notConnectionDb.h -o moc_notConnectionDb.cpp

moc_UbdaterClass.cpp: include/db/dbFinder.h \
		include/ObjectsUpdater.h \
		include/ObjectClass.h \
		include/DeviceClass.h \
		include/baseDevice.h \
		include/db/dbMainObject.h \
		include/db/dbclass.h \
		include/FaultsClass.h \
		include/ActiveDev.h \
		include/UbdaterClass.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) include/UbdaterClass.h -o moc_UbdaterClass.cpp

moc_baseDevice.cpp: include/baseDevice.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) include/baseDevice.h -o moc_baseDevice.cpp

moc_BSPurWid.cpp: include/ObjectClass.h \
		include/DeviceClass.h \
		include/baseDevice.h \
		include/db/dbMainObject.h \
		include/db/dbclass.h \
		include/db/dbDevices.h \
		include/BSPurWid.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) include/BSPurWid.h -o moc_BSPurWid.cpp

moc_OtherDevWid.cpp: include/db/dbDevices.h \
		include/db/dbclass.h \
		include/OtherDevWid.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) include/OtherDevWid.h -o moc_OtherDevWid.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_rightWidget.h ui_ClockFrame.h ui_SetName.h ui_StateChanFrame.h ui_mainFrame.h ui_ObjectPA.h ui_notConnectionDb.h
compiler_uic_clean:
	-$(DEL_FILE) ui_rightWidget.h ui_ClockFrame.h ui_SetName.h ui_StateChanFrame.h ui_mainFrame.h ui_ObjectPA.h ui_notConnectionDb.h
ui_rightWidget.h: ui/rightWidget.ui \
		include/frameborder.h
	/usr/lib/i386-linux-gnu/qt4/bin/uic ui/rightWidget.ui -o ui_rightWidget.h

ui_ClockFrame.h: ui/ClockFrame.ui
	/usr/lib/i386-linux-gnu/qt4/bin/uic ui/ClockFrame.ui -o ui_ClockFrame.h

ui_SetName.h: ui/SetName.ui
	/usr/lib/i386-linux-gnu/qt4/bin/uic ui/SetName.ui -o ui_SetName.h

ui_StateChanFrame.h: ui/StateChanFrame.ui
	/usr/lib/i386-linux-gnu/qt4/bin/uic ui/StateChanFrame.ui -o ui_StateChanFrame.h

ui_mainFrame.h: ui/mainFrame.ui
	/usr/lib/i386-linux-gnu/qt4/bin/uic ui/mainFrame.ui -o ui_mainFrame.h

ui_ObjectPA.h: ui/ObjectPA.ui
	/usr/lib/i386-linux-gnu/qt4/bin/uic ui/ObjectPA.ui -o ui_ObjectPA.h

ui_notConnectionDb.h: ui/notConnectionDb.ui
	/usr/lib/i386-linux-gnu/qt4/bin/uic ui/notConnectionDb.ui -o ui_notConnectionDb.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: src/main.cpp include/MainWindow.h \
		include/define.h \
		include/rightWidget.h \
		include/StandBut.h \
		include/butparent.h \
		include/baseDevice.h \
		include/DeviceClass.h \
		ui_rightWidget.h \
		include/ObjectClass.h \
		include/db/dbMainObject.h \
		include/db/dbclass.h \
		include/MainFrame.h \
		ui_mainFrame.h \
		include/StateChanFrame.h \
		include/DeviceBut.h \
		ui_StateChanFrame.h \
		include/db/dbDevices.h \
		include/BSPurWid.h \
		include/OtherDevWid.h \
		include/ChanButton.h \
		include/ObjectsUpdater.h \
		include/SetNameDialog.h \
		ui_SetName.h \
		include/ObjectPA.h \
		include/notConnectionDb.h \
		include/UbdaterClass.h \
		include/db/dbFinder.h \
		include/FaultsClass.h \
		include/ActiveDev.h \
		include/util/Singleton.h \
		include/util/MyException.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

MainWindow.o: src/MainWindow.cpp include/MainWindow.h \
		include/define.h \
		include/rightWidget.h \
		include/StandBut.h \
		include/butparent.h \
		include/baseDevice.h \
		include/DeviceClass.h \
		ui_rightWidget.h \
		include/ObjectClass.h \
		include/db/dbMainObject.h \
		include/db/dbclass.h \
		include/MainFrame.h \
		ui_mainFrame.h \
		include/StateChanFrame.h \
		include/DeviceBut.h \
		ui_StateChanFrame.h \
		include/db/dbDevices.h \
		include/BSPurWid.h \
		include/OtherDevWid.h \
		include/ChanButton.h \
		include/ObjectsUpdater.h \
		include/SetNameDialog.h \
		ui_SetName.h \
		include/ObjectPA.h \
		include/notConnectionDb.h \
		include/UbdaterClass.h \
		include/db/dbFinder.h \
		include/FaultsClass.h \
		include/ActiveDev.h \
		include/blinkingclass.h \
		include/util/Singleton.h \
		include/util/MyException.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainWindow.o src/MainWindow.cpp

StateChanFrame.o: src/StateChanFrame.cpp include/StateChanFrame.h \
		include/DeviceBut.h \
		include/butparent.h \
		include/baseDevice.h \
		ui_StateChanFrame.h \
		include/define.h \
		include/db/dbDevices.h \
		include/db/dbclass.h \
		include/BSPurWid.h \
		include/ObjectClass.h \
		include/DeviceClass.h \
		include/db/dbMainObject.h \
		include/OtherDevWid.h \
		include/util/Singleton.h \
		include/util/MyException.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o StateChanFrame.o src/StateChanFrame.cpp

MainFrame.o: src/MainFrame.cpp include/MainFrame.h \
		ui_mainFrame.h \
		include/StateChanFrame.h \
		include/DeviceBut.h \
		include/butparent.h \
		include/baseDevice.h \
		ui_StateChanFrame.h \
		include/define.h \
		include/db/dbDevices.h \
		include/db/dbclass.h \
		include/BSPurWid.h \
		include/ObjectClass.h \
		include/DeviceClass.h \
		include/db/dbMainObject.h \
		include/OtherDevWid.h \
		include/ChanButton.h \
		include/ObjectsUpdater.h \
		include/SetNameDialog.h \
		ui_SetName.h \
		include/ClockFrame.h \
		ui_ClockFrame.h \
		include/util/Singleton.h \
		include/util/MyException.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainFrame.o src/MainFrame.cpp

rightWidget.o: src/rightWidget.cpp include/rightWidget.h \
		include/StandBut.h \
		include/butparent.h \
		include/baseDevice.h \
		include/DeviceClass.h \
		ui_rightWidget.h \
		include/ObjectClass.h \
		include/db/dbMainObject.h \
		include/db/dbclass.h \
		include/util/Singleton.h \
		include/util/MyException.h \
		include/ObjectsUpdater.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rightWidget.o src/rightWidget.cpp

DeviceBut.o: src/DeviceBut.cpp include/DeviceBut.h \
		include/butparent.h \
		include/baseDevice.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DeviceBut.o src/DeviceBut.cpp

ClockFrame.o: src/ClockFrame.cpp include/ClockFrame.h \
		ui_ClockFrame.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ClockFrame.o src/ClockFrame.cpp

SetNameDialog.o: src/SetNameDialog.cpp include/SetNameDialog.h \
		ui_SetName.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SetNameDialog.o src/SetNameDialog.cpp

ChanButton.o: src/ChanButton.cpp include/ChanButton.h \
		include/butparent.h \
		include/baseDevice.h \
		include/ObjectsUpdater.h \
		include/ObjectClass.h \
		include/DeviceClass.h \
		include/db/dbMainObject.h \
		include/db/dbclass.h \
		include/SetNameDialog.h \
		ui_SetName.h \
		include/util/Singleton.h \
		include/util/MyException.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ChanButton.o src/ChanButton.cpp

ObjectPA.o: src/ObjectPA.cpp include/ObjectPA.h \
		ui_ObjectPA.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ObjectPA.o src/ObjectPA.cpp

blinkingclass.o: src/blinkingclass.cpp include/blinkingclass.h \
		include/butparent.h \
		include/baseDevice.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o blinkingclass.o src/blinkingclass.cpp

butparent.o: src/butparent.cpp include/butparent.h \
		include/baseDevice.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o butparent.o src/butparent.cpp

StandBut.o: src/StandBut.cpp include/StandBut.h \
		include/butparent.h \
		include/baseDevice.h \
		include/DeviceClass.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o StandBut.o src/StandBut.cpp

dbclass.o: src/db/dbclass.cpp include/db/dbclass.h \
		include/util/MyException.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dbclass.o src/db/dbclass.cpp

dbMainObject.o: src/db/dbMainObject.cpp include/db/dbMainObject.h \
		include/db/dbclass.h \
		include/util/Singleton.h \
		include/util/MyException.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dbMainObject.o src/db/dbMainObject.cpp

DeviceClass.o: src/DeviceClass.cpp include/DeviceClass.h \
		include/baseDevice.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DeviceClass.o src/DeviceClass.cpp

ObjectClass.o: src/ObjectClass.cpp include/ObjectClass.h \
		include/DeviceClass.h \
		include/baseDevice.h \
		include/db/dbMainObject.h \
		include/db/dbclass.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ObjectClass.o src/ObjectClass.cpp

ObjectsUpdater.o: src/ObjectsUpdater.cpp include/ObjectsUpdater.h \
		include/ObjectClass.h \
		include/DeviceClass.h \
		include/baseDevice.h \
		include/db/dbMainObject.h \
		include/db/dbclass.h \
		include/util/MyException.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ObjectsUpdater.o src/ObjectsUpdater.cpp

MyException.o: src/util/MyException.cpp include/util/MyException.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MyException.o src/util/MyException.cpp

dbFinder.o: src/db/dbFinder.cpp include/db/dbFinder.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dbFinder.o src/db/dbFinder.cpp

notConnectionDb.o: src/notConnectionDb.cpp include/notConnectionDb.h \
		ui_notConnectionDb.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o notConnectionDb.o src/notConnectionDb.cpp

FaultsClass.o: src/FaultsClass.cpp include/FaultsClass.h \
		include/db/dbMainObject.h \
		include/db/dbclass.h \
		include/ObjectsUpdater.h \
		include/ObjectClass.h \
		include/DeviceClass.h \
		include/baseDevice.h \
		include/util/Singleton.h \
		include/util/MyException.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FaultsClass.o src/FaultsClass.cpp

UbdaterClass.o: src/UbdaterClass.cpp include/UbdaterClass.h \
		include/db/dbFinder.h \
		include/ObjectsUpdater.h \
		include/ObjectClass.h \
		include/DeviceClass.h \
		include/baseDevice.h \
		include/db/dbMainObject.h \
		include/db/dbclass.h \
		include/FaultsClass.h \
		include/ActiveDev.h \
		include/util/MyException.h \
		include/util/Singleton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o UbdaterClass.o src/UbdaterClass.cpp

baseDevice.o: src/baseDevice.cpp include/baseDevice.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o baseDevice.o src/baseDevice.cpp

ActiveDev.o: src/ActiveDev.cpp include/ActiveDev.h \
		include/db/dbMainObject.h \
		include/db/dbclass.h \
		include/ObjectsUpdater.h \
		include/ObjectClass.h \
		include/DeviceClass.h \
		include/baseDevice.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ActiveDev.o src/ActiveDev.cpp

dbDevices.o: src/db/dbDevices.cpp include/db/dbDevices.h \
		include/db/dbclass.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dbDevices.o src/db/dbDevices.cpp

BSPurWid.o: src/BSPurWid.cpp include/BSPurWid.h \
		include/ObjectClass.h \
		include/DeviceClass.h \
		include/baseDevice.h \
		include/db/dbMainObject.h \
		include/db/dbclass.h \
		include/db/dbDevices.h \
		include/ObjectsUpdater.h \
		include/util/Singleton.h \
		include/util/MyException.h \
		include/PurBut.h \
		include/StandBut.h \
		include/butparent.h \
		include/BSPurBut.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BSPurWid.o src/BSPurWid.cpp

PurBut.o: src/PurBut.cpp include/PurBut.h \
		include/StandBut.h \
		include/butparent.h \
		include/baseDevice.h \
		include/DeviceClass.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PurBut.o src/PurBut.cpp

BSPurBut.o: src/BSPurBut.cpp include/BSPurBut.h \
		include/StandBut.h \
		include/butparent.h \
		include/baseDevice.h \
		include/DeviceClass.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BSPurBut.o src/BSPurBut.cpp

OtherDevWid.o: src/OtherDevWid.cpp include/OtherDevWid.h \
		include/db/dbDevices.h \
		include/db/dbclass.h \
		include/OtherDevBut.h \
		include/StandBut.h \
		include/butparent.h \
		include/baseDevice.h \
		include/DeviceClass.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o OtherDevWid.o src/OtherDevWid.cpp

OtherDevBut.o: src/OtherDevBut.cpp include/OtherDevBut.h \
		include/StandBut.h \
		include/butparent.h \
		include/baseDevice.h \
		include/DeviceClass.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o OtherDevBut.o src/OtherDevBut.cpp

moc_StateChanFrame.o: moc_StateChanFrame.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_StateChanFrame.o moc_StateChanFrame.cpp

moc_DeviceBut.o: moc_DeviceBut.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_DeviceBut.o moc_DeviceBut.cpp

moc_rightWidget.o: moc_rightWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rightWidget.o moc_rightWidget.cpp

moc_ClockFrame.o: moc_ClockFrame.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ClockFrame.o moc_ClockFrame.cpp

moc_ChanButton.o: moc_ChanButton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ChanButton.o moc_ChanButton.cpp

moc_SetNameDialog.o: moc_SetNameDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SetNameDialog.o moc_SetNameDialog.cpp

moc_MainWindow.o: moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MainWindow.o moc_MainWindow.cpp

moc_ObjectPA.o: moc_ObjectPA.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ObjectPA.o moc_ObjectPA.cpp

moc_MainFrame.o: moc_MainFrame.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MainFrame.o moc_MainFrame.cpp

moc_blinkingclass.o: moc_blinkingclass.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_blinkingclass.o moc_blinkingclass.cpp

moc_butparent.o: moc_butparent.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_butparent.o moc_butparent.cpp

moc_StandBut.o: moc_StandBut.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_StandBut.o moc_StandBut.cpp

moc_frameborder.o: moc_frameborder.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_frameborder.o moc_frameborder.cpp

moc_DeviceClass.o: moc_DeviceClass.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_DeviceClass.o moc_DeviceClass.cpp

moc_ObjectClass.o: moc_ObjectClass.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ObjectClass.o moc_ObjectClass.cpp

moc_dbFinder.o: moc_dbFinder.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dbFinder.o moc_dbFinder.cpp

moc_notConnectionDb.o: moc_notConnectionDb.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_notConnectionDb.o moc_notConnectionDb.cpp

moc_UbdaterClass.o: moc_UbdaterClass.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_UbdaterClass.o moc_UbdaterClass.cpp

moc_baseDevice.o: moc_baseDevice.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_baseDevice.o moc_baseDevice.cpp

moc_BSPurWid.o: moc_BSPurWid.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_BSPurWid.o moc_BSPurWid.cpp

moc_OtherDevWid.o: moc_OtherDevWid.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_OtherDevWid.o moc_OtherDevWid.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

